name: ScuphUtils
version: 1.2
main: com.scuph.scuphsutilities.ScuphsUtilities
description: Scuph's utility plugin for TotalFreedom!
authors: [Scuph]
commands:
    information:
        usage: /<command>
        description: Info about the plugin and server
        aliases: []
        permission: utils.info
    developer:
        usage: /<command>
        description: Find the server's developers
        aliases: dev
        permission: utils.dev
    staff:
        usage: /<command>
        description: Find the server's staff team
        aliases: staffteam
        permission: utils.staff
    welcome:
        usage: /<command>
        description: Do this when a new player joins.
        aliases: wc
        permission: utils.welcome
    iwantadmin:
        usage: /<command>
        description: Ask for admin
        aliases: ai
        permission: utils.iwantadmin
    requesthelp:
        usage: /<command>
        description: Request a staff member's help
        aliases: ineedhelp
        permission: utils.requesthelp
    owner:
        usage: /<command>
        description: Find the server's owner
        aliases: founder
        permission: utils.owner
        
